### ISSUE TITLE
 Q: How to forward data to a local tcp server? 

### ISSUE THREAD

**Issue by oleid** [spebern/async-ssh2#11]
Hey there,

to access a host behind a ssh server, I  need to to SSH forwarding (or set a proxy connection in my ssh config).  Naturally, I can do the forwarding manually. But it would be nice to be able to do it automatically. Thus, I tried something like:

```rust
async fn forward_connection(sess: &mut async_ssh2::Session, w: &str, port: u16) -> Result<(), Box<dyn std::error::Error>>
{
    use futures::join;

    let listener = async_std::net::TcpListener::bind("localhost:0").await?;

    let mut incoming = listener.incoming();

    while let Some(stream) = incoming.next().await {
        let stream = stream?;
        let ssh = sess.channel_direct_tcpip(w, port, None).await?;

        let (tcp_rx, tcp_tx) = &mut (&stream, &stream);
        let (ssh_rx, ssh_tx, ) =&mut (ssh, &ssh);

        let a_to_b = async_std::io::copy(tcp_rx, ssh_tx);
        let b_to_a = async_std::io::copy(ssh_rx, tcp_tx);

        join!(a_to_b, b_to_a).await
    }
    Ok(())
}
``` 

This is a modified version of `async_std`'s TcpListener example (https://docs.rs/async-std/1.6.0-beta.1/async_std/net/struct.TcpListener.html). Yet, it doesn't work :

```
error[E0277]: the trait bound `&async_ssh2::channel::Channel: futures_io::if_std::AsyncWrite` is not satisfied
   --> src/main.rs:120:50
    |
120 |         let a_to_b = async_std::io::copy(tcp_rx, ssh_tx);
    |                                                  ^^^^^^ the trait `futures_io::if_std::AsyncWrite` is not implemented for `&async_ssh2::channel::Channel`
    | 
```

What would be the recommended way to split a channel to forward it to a socket (unix or tcp)?

I have a feeling that it might be not possible at the moment. Or I missed something.

Or related - what would be the recommended way to _dynamically_ access SSH servers _behind_ another ssh server?

**Comment by spebern** [comment]
The problem of why this doesn't compile is that `AsyncWrite` is indeed not implemented for `&async_ssh2::channel::Channel`. It is only implemented for `&mut async_ssh2::channel::Channel`.

`join!` can potentially run futures on the same time if the underlying executor is multithreaded, which
should cause some problems, since there are shared mutable references to the session and the tcp stream.

Another note is, that I'd probably use a new `Session` for each incoming connection, because the underlying `ssh2` crate locks briefly when calling methods, to be a safe wrapper around the c library.

One solution that might work (I have not tested it, I only compiled it) is:

```rust
use async_std::prelude::*;
use futures::io::AsyncReadExt;

async fn forward_connection(sess: &mut async_ssh2::Session, w: &str, port: u16) -> Result<(), Box<dyn std::error::Error>>
{
    use futures::join;

    let listener = async_std::net::TcpListener::bind("localhost:0").await?;

    let mut incoming = listener.incoming();

    while let Some(stream) = incoming.next().await {
        // TODO: I would create a session for each incoming connection, so that the underlying
        // tcp stream of the session is not shared for all incoming connections

        let mut stream = stream?;
        let ssh = sess.channel_direct_tcpip(w, port, None).await?;

        // split into readers and writers
        let (mut tcp_rx, mut tcp_tx) = stream.split();
        let (mut ssh_rx, mut ssh_tx) = ssh.split();

        let a_to_b = futures::io::copy(&mut tcp_rx, &mut ssh_tx);
        let b_to_a = futures::io::copy(&mut ssh_rx, &mut tcp_tx);

        join!(a_to_b, b_to_a);

    }
    Ok(())
}
```

I hope this helps you somehow!

**Comment by oleid** [comment]
Ah, split did the trick, thanks! It would seem on `async_std` you can simply borrow the stream and then you're fine.

**Comment by spebern** [comment]
You are welcome!
