### ISSUE TITLE
Thread blocks on sess.handshake()

### ISSUE THREAD

**Issue by 0xdeafbeef** [spebern/async-ssh2#6]
runing such [code](https://github.com/0xd34b33f/ansible-rs/blob/f56adf050ec633aac50d7d3505414d480141671f/src/main.rs#L56
) leads to such output:
```
[src\main.rs:67] format!("Tcp connection intialized {}", & hostname) = "Tcp connection intialized 10.36.78.43:22"
[src\main.rs:74] format!("Session is built {}", & hostname) = "Session is built 10.36.78.43:22"
[src\main.rs:78] format!("Tcp stream is set : {}", & hostname) = "Tcp stream is set : 10.36.78.43:22"
```
Maybe i'm bad cooking async code
And waiting doesn't help at all.
Thats all packets, which are sent to the host.
![image](https://user-images.githubusercontent.com/32823131/73069055-cbf82600-3ebd-11ea-94b3-e67c8b16ca8e.png)

**Comment by 0xdeafbeef** [comment]
To reproduce it, you can clone my repo on test branch and run `cargo run -- --hosts  path`, where path is path to file with ip address.

**Comment by spebern** [comment]
I cannot reproduce the blocking handshake. If I run the code it fails somewhen later, because I do not have the same setup as you do. Does the code work with `ssh2-rs`?

**Comment by 0xdeafbeef** [comment]
It worked on 0.6 version, untested on version 0.7. I'll provide additional info on Monday

**Comment by 0xdeafbeef** [comment]
I fixed my code, now u can clone it and check

**Comment by 0xdeafbeef** [comment]
`git checkout --track origin/test`
`cargo run -- --hosts .\hosts.txt`
hosts must conatain any hostname / ip address with opened 22 port
Tested sync version with same setup:
```[{"result":"[-42] failed connecting agent","hostname":"10.36.78.40:22","process_time":"92ms 147us 700ns","status":false}]```
So, it doesn't blocks and works as expected.
If you need any adddtional info - i'll provide it

**Comment by spebern** [comment]
I tried to reproduce the code with both ssh2 and async-ssh2 and I cannot reproduce it. For me the handshake of both versions works and does not block.

Which OS are you using?

**Comment by 0xdeafbeef** [comment]
Windows 10 :(

**Comment by spebern** [comment]
I was able to reproduce this on Windows 10. On linux it works. The problem is that the future does not get polled again, even though I registered it. Gonna need a little more time to debug this.

**Comment by 0xdeafbeef** [comment]
Thank you!

**Comment by spebern** [comment]
I will wait until `tokio` updates to `mio 0.7`, because there will be a lot of changes, which will also make the async connect much easier.

**Comment by 0xdeafbeef** [comment]
So, will it work after changing runtime to smol?

**Comment by spebern** [comment]
I think it should work. Just make sure that you either
- first create the session, then connect to the tcp stream and set it in the session
- or run smol run somewhen before

Smol will simplify this in the future, but this is the only detail you need to watch out for now I think.

I published a beta on crates.io.

**Comment by 0xdeafbeef** [comment]
It works :)
